### ISSUE TITLE
chore: nightly synthtool run

### ISSUE THREAD

**Issue by bcoe** [bcoe/demo-metadata-response-issues#2]
```
Upstream-PR: 
  Source-Repo: googleapis/synthtool
  Original-Commit-: docs: updates the README body.
Upstream-PR:
  Source-Repo: googleapis/googleapis
  Original-Commit-Message: run the generator
Upstream-PR:
  Source-Repo: googleapis/typescript-microgenerator
  Original-Commit: feat: adds sync iteration
```
